---
- name: Authentifier et ajouter un domaine sur FortiMail
  hosts: localhost
  gather_facts: no
  vars:
    fortimail_host: "192.168.171.24"
    fortimail_username: "admin"
    fortimail_password: "password"
    new_domain: "exq.local"
    login_url: "https://{{ fortimail_host }}/api/v1/AdminLogin/"
    domain_url: "https://{{ fortimail_host }}/api/v1/Domain/"

  tasks:
    - name: Authentification à FortiMail via API REST
      uri:
        url: "{{ login_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        validate_certs: no
        return_content: yes
      register: login_response

    - name: Extraire le cookie APSCOOKIE
      set_fact:
        session_cookie: "{{ login_response.set_cookie | regex_search('APSCOOKIE[^;]+') }}"

    - name: Extraire le token CSRF
      set_fact:
        csrf_token: "{{ login_response.json.csrf_token }}"

    - name: Ajouter le domaine "{{ new_domain }}"
      uri:
        url: "{{ domain_url }}{{ new_domain }}/"
        method: POST
        headers:
          Content-Type: "application/json"
          Cookie: "{{ session_cookie }}"
          X-Csrf-Token: "{{ csrf_token }}"
        body_format: json
        body:
          mkey: "{{ new_domain }}"
          domain: "{{ new_domain }}"
          type: "local"  # ou "relay" selon ton besoin
          enabled: true
          description: "Ajouté via Ansible"
        validate_certs: no
        return_content: yes
      register: add_domain_response

    - name: Afficher la réponse de l'ajout de domaine
      debug:
        var: add_domain_response.json
