---
- name: Authentifier sur FortiMail et récupérer le cookie + CSRF token
  hosts: localhost
  gather_facts: no
  vars:
    fortimail_host: "192.168.171.24"
    fortimail_username: "admin"
    fortimail_password: "password"
    login_url: "https://{{ fortimail_host }}/api/v1/AdminLogin/"

  tasks:
    - name: Authentification à FortiMail via API REST
      uri:
        url: "{{ login_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        validate_certs: no
        return_content: yes
      register: login_response

    - name: Extraire le cookie APSCOOKIE
      set_fact:
        session_cookie: "{{ login_response.set_cookie | regex_search('APSCOOKIE[^;]+') }}"

    - name: Extraire le token CSRF
      set_fact:
        csrf_token: "{{ login_response.json.csrf_token }}"

    - name: Afficher le cookie et le token
      debug:
        msg:
          - "Cookie: {{ session_cookie }}"
          - "CSRF Token: {{ csrf_token }}"
