---
- name: Authentifier sur FortiMail et récupérer les interfaces
  hosts: localhost
  gather_facts: no
  vars:
    fortimail_host: "192.168.171.24"
    fortimail_username: "admin"
    fortimail_password: "password"
    login_url: "https://{{ fortimail_host }}/api/v1/AdminLogin/"
    interface_url: "https://{{ fortimail_host }}/api/v1/SysInterface/"

  tasks:
    - name: Authentification à FortiMail via API REST
      uri:
        url: "{{ login_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        validate_certs: no
        return_content: yes
      register: login_response

    - name: Extraire le cookie APSCOOKIE
      set_fact:
        session_cookie: "{{ login_response.set_cookie | regex_search('APSCOOKIE[^;]+') }}"

    - name: Extraire le token CSRF
      set_fact:
        csrf_token: "{{ login_response.json.csrf_token }}"

    - name: Récupérer la liste des interfaces réseau
      uri:
        url: "{{ interface_url }}"
        method: GET
        headers:
          Content-Type: "application/json"
          Cookie: "{{ session_cookie }}"
          X-Csrf-Token: "{{ csrf_token }}"
        validate_certs: no
        return_content: yes
      register: interfaces_response

    - name: Afficher la réponse JSON des interfaces
      debug:
        var: interfaces_response.json
