---
- name: Authentifier et récupérer la liste des domaines sur FortiMail
  hosts: localhost
  gather_facts: no

  vars:
    fortimail_host: "192.168.171.24"
    fortimail_username: "admin"
    fortimail_password: "password"
    login_url: "https://{{ fortimail_host }}/api/v1/AdminLogin/"
    domains_url: "https://{{ fortimail_host }}/api/v1/Domain/"

  tasks:

    - name: Authentification à FortiMail
      uri:
        url: "{{ login_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        validate_certs: no
        return_content: yes
      register: login_response

    - name: Extraire le cookie APSCOOKIE
      set_fact:
        session_cookie: "{{ login_response.set_cookie | regex_search('APSCOOKIE[^;]+') }}"

    - name: Extraire le token CSRF
      set_fact:
        csrf_token: "{{ login_response.json.csrf_token }}"

    - name: Récupérer la liste des domaines
      uri:
        url: "{{ domains_url }}"
        method: GET
        headers:
          Content-Type: "application/json"
          X-Csrf-Token: "{{ csrf_token }}"
          Cookie: "{{ session_cookie }}"
        validate_certs: no
        return_content: yes
      register: domain_list

    - name: Afficher la liste des domaines
      debug:
        var: domain_list.json.collection
