---
- name: Authentifier et configurer l'interface FortiMail
  hosts: localhost
  gather_facts: no

  vars:
    fortimail_host: "192.168.171.24"
    fortimail_username: "admin"
    fortimail_password: "password"
    interface_name: "port2"
    new_ip: "172.25.2.24/24"
    login_url: "https://{{ fortimail_host }}/api/v1/AdminLogin/"
    interface_url: "https://{{ fortimail_host }}/api/v1/SysInterface/{{ interface_name }}/"

  tasks:

    - name: Authentification à FortiMail
      uri:
        url: "{{ login_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        validate_certs: no
        return_content: yes
      register: login_response

    - name: Extraire le cookie APSCOOKIE
      set_fact:
        session_cookie: "{{ login_response.set_cookie | regex_search('APSCOOKIE[^;]+') }}"

    - name: Extraire le token CSRF
      set_fact:
        csrf_token: "{{ login_response.json.csrf_token }}"

    - name: Mise à jour de l'adresse IP de l'interface {{ interface_name }}
      uri:
        url: "{{ interface_url }}"
        method: PUT
        headers:
          Content-Type: "application/json"
          X-Csrf-Token: "{{ csrf_token }}"
          Cookie: "{{ session_cookie }}"
        body_format: json
        body:
          name: "{{ interface_name }}"
          ip: "{{ new_ip }}"
          status: 1
        validate_certs: no
        return_content: yes
      register: update_result

    - name: Afficher le résultat de la mise à jour
      debug:
        var: update_result.json
